# Generated by Django 4.0.6 on 2022-07-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customershowroompurchase_rice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customershowroompurchase',
            old_name='rice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='customershowroompurchase',
            old_name='rice_currency',
            new_name='price_currency',
        ),
    ]
