# Generated by Django 4.0.6 on 2022-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_rice_customershowroompurchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
