# Generated by Django 4.0.6 on 2022-08-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
    ]
