# Generated by Django 4.0.6 on 2022-07-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_showroom', '0001_initial'),
        ('dealer', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquecustomer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='showroomcustomersale',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.car'),
        ),
        migrations.AddField(
            model_name='showroomcustomersale',
            name='car_showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_showroom.carshowroom'),
        ),
        migrations.AddField(
            model_name='showroomcustomersale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='showroomcustomersale',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.discount'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='sales',
            field=models.ManyToManyField(through='car_showroom.ShowroomCustomerSale', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='unique_customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_showroom.uniquecustomer'),
        ),
    ]
