# Generated by Django 4.0.6 on 2022-07-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0003_alter_carshowroom_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='showroomcustomersale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uniquecustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
