# Generated by Django 4.0.6 on 2022-07-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0004_alter_carshowroom_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='unique_customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_showroom.uniquecustomer'),
        ),
        migrations.AlterField(
            model_name='showroomcustomersale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uniquecustomer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
