# Generated by Django 4.0.7 on 2022-08-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0006_showroomcarsforsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshowroom',
            name='unique_customers',
        ),
        migrations.AddField(
            model_name='uniquecustomer',
            name='customer_showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_showroom.carshowroom'),
        ),
    ]
