# Generated by Django 4.0.7 on 2022-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0008_alter_showroomcustomersale_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomcustomersale',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
