# Generated by Django 4.0.7 on 2022-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0009_alter_showroomcustomersale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomcustomersale',
            name='sale_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
