# Generated by Django 4.0.6 on 2022-07-22 10:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('gearbox', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=200)),
                ('engine_volume', models.FloatField()),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue'), ('black', 'black'), ('white', 'white')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('customers_amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('discount', models.PositiveIntegerField()),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='DealerShowroomSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.carforsale')),
                ('car_showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_showroom.carshowroom')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.dealer')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dealer',
            name='sales',
            field=models.ManyToManyField(through='dealer.DealerShowroomSale', to='car_showroom.carshowroom'),
        ),
        migrations.AddField(
            model_name='carforsale',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.dealer'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('engine_volume__gte', 0.0)), name='car_engine_volume_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 1900)), name='car_year_gte_then_1900'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='discount_in_range_of_0_100'),
        ),
    ]
