# Generated by Django 4.0.6 on 2022-07-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0006_showroomcarsforsale'),
        ('dealer', '0005_dealershowroomsale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_showroom.carshowroom'),
        ),
    ]
