# Generated by Django 4.0.6 on 2022-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_discount_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershowroomsale',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.discount'),
        ),
    ]
